FROM alpine:latest

RUN apk update && apk add \
    nodejs \
    openssl \
    unzip

ADD nodepki* /root/

WORKDIR /root
RUN unzip nodepki-0.1.1.zip
RUN unzip nodepki-client-0.1.0.zip

### Add nodepki config file
ADD config.yml /root/nodepki-0.1.1/

WORKDIR /root/nodepki-0.1.1
RUN npm install
RUN node genpki.js

#EXPOSE 8081
#EXPOSE 2560
#EXPOSE 2561


CMD node server.js
